[2025-03-24T13:50:25.832-1000] {processor.py:186} INFO - Started process (PID=9523) to work on /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T13:50:25.832-1000] {processor.py:914} INFO - Processing file /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-24T13:50:25.832-1000] {logging_mixin.py:190} INFO - [2025-03-24T13:50:25.832-1000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T13:50:25.841-1000] {logging_mixin.py:190} INFO - [2025-03-24T13:50:25.841-1000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-24T13:50:25.842-1000] {logging_mixin.py:190} INFO - [2025-03-24T13:50:25.841-1000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-24T13:50:25.842-1000] {processor.py:927} WARNING - No viable dags retrieved from /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-24T13:50:25.862-1000] {processor.py:208} INFO - Processing /opt/anaconda3/envs/titanic/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.050 seconds
